apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::507104785249:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-H6CA7BCPK6Y0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::507104785249:role/UdacityFlaskDeployCBKubectlRole
      username: build    
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-31T16:08:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1612"
  uid: cf59b682-ad5c-453f-9eeb-8a84ebfe0ef9
